name: latex

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            export DOCUMENT_VERSION="prerelease-${GITHUB_REF##*/}-$(date -Iseconds)"
            ./compileall.sh

      - uses: actions/upload-artifact@v2
        with:
          name: rendered pdf
          path: main.pdf
